
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Administrator
 */
public class VentanaAhorcado extends javax.swing.JFrame {

    String palabraOculta = "CETYS";
//contador de fallos
    int numeroFallos = 0; 
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        //aqui va el código que poniamos en eel run en ACM
    }

    @Override
    public void paint(Graphics g) {
        super.paint(g);
        //con esto indicamos que vamos a dibujar en el panel 
        g = jPanel1.getGraphics();
        Image miImagen = null;
        try {
            int numeroFallos = 0;
            //cargamos una imagen
            switch (numeroFallos){
                case 0: miImagen = ImageIO.read(getClass().getResource("/ahorcado_0.png")); break;
                case 1: miImagen = ImageIO.read(getClass().getResource("/ahorcado_1.png")); break;
                case 2: miImagen = ImageIO.read(getClass().getResource("/ahorcado_2.png")); break;
                case 3: miImagen = ImageIO.read(getClass().getResource("/ahorcado_3.png")); break;
                case 4: miImagen = ImageIO.read(getClass().getResource("/ahorcado_4.png")); break;
                case 5: miImagen = ImageIO.read(getClass().getResource("/ahorcado_5.png")); break;
                case 6: miImagen = ImageIO.read(getClass().getResource("/ahorcado_fin.png")); break;
                case -1: miImagen = ImageIO.read(getClass().getResource("/acertasteTodo.png")); break;
                default : miImagen = ImageIO.read(getClass().getResource("/ahorcado_fin.png")); break;
            } 
           
        } catch (IOException ex) {

        }
        //Dibujo la imagen en el panel y lo ajusto al panel
        g.drawImage(miImagen, 0, 0, jPanel1.getWidth(), jPanel1.getHeight(), null);
    }

    private void chequeaLetra(JButton boton) {
       
        if(boton.isEnabled()){
        String letra = (boton.getText());
       //deshabilitad el boton despues de darle

        boton.setEnabled(false);
        //hsta aqui
        String palabraConGuiones = jLabel1.getText();

        if (palabraOculta.contains(letra)) {
            for (int i = 0; i < palabraOculta.length(); i++) {
                if (palabraOculta.charAt(i) == letra.charAt(0)) {
                    palabraConGuiones = palabraConGuiones.substring(0, 2 * i)
                            + letra
                            + palabraConGuiones.substring(2 * i + 1);
                }
            }
            jLabel1.setText(palabraConGuiones);
            //Compruebo si la palabra con guiones o no
            //si no hay guiones no hago nada , porque no he ganado la partida
            //y si no hay guiones, indico de alguna forma que he ganado la partida
            if (!palabraConGuiones.contains("_")){
                numeroFallos = -1;
                
            }
        }
        else{
            numeroFallos++;
            
            
        }
    }
        repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButtonA = new javax.swing.JButton();
        jButtonB = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonD = new javax.swing.JButton();
        jButtonE = new javax.swing.JButton();
        jButtonF = new javax.swing.JButton();
        jButtonG = new javax.swing.JButton();
        jButtonH = new javax.swing.JButton();
        jButtonI = new javax.swing.JButton();
        jButtonJ = new javax.swing.JButton();
        jButtonK = new javax.swing.JButton();
        jButtonL = new javax.swing.JButton();
        jButtonM = new javax.swing.JButton();
        jButtonN = new javax.swing.JButton();
        jButtonÑ = new javax.swing.JButton();
        jButtonO = new javax.swing.JButton();
        jButtonP = new javax.swing.JButton();
        jButtonQ = new javax.swing.JButton();
        jButtonR = new javax.swing.JButton();
        jButtonS = new javax.swing.JButton();
        jButtonT = new javax.swing.JButton();
        jButtonU = new javax.swing.JButton();
        jButtonV = new javax.swing.JButton();
        jButtonW = new javax.swing.JButton();
        jButtonX = new javax.swing.JButton();
        jButtonY = new javax.swing.JButton();
        jButtonZ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 38)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("_ _ _ _ _ ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 410, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jButtonA.setText("A");
        jButtonA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAMousePressed(evt);
            }
        });
        getContentPane().add(jButtonA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, 31));

        jButtonB.setText("B");
        jButtonB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBMousePressed(evt);
            }
        });
        getContentPane().add(jButtonB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 40, 31));

        jButtonC.setText("C");
        jButtonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonCMousePressed(evt);
            }
        });
        getContentPane().add(jButtonC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 42, 31));

        jButtonD.setText("E");
        jButtonD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDMousePressed(evt);
            }
        });
        getContentPane().add(jButtonD, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 42, 31));

        jButtonE.setText("D");
        jButtonE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEMousePressed(evt);
            }
        });
        getContentPane().add(jButtonE, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, 44, 31));

        jButtonF.setText("G");
        jButtonF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonFMousePressed(evt);
            }
        });
        jButtonF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, 41, 31));

        jButtonG.setText("F");
        jButtonG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonGMousePressed(evt);
            }
        });
        getContentPane().add(jButtonG, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 500, 40, 31));

        jButtonH.setText("H");
        jButtonH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonHMousePressed(evt);
            }
        });
        getContentPane().add(jButtonH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, 31));

        jButtonI.setText("I");
        jButtonI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonIMousePressed(evt);
            }
        });
        getContentPane().add(jButtonI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, 40, 31));

        jButtonJ.setText("J");
        jButtonJ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonJMousePressed(evt);
            }
        });
        jButtonJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 42, 31));

        jButtonK.setText("K");
        jButtonK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonKMousePressed(evt);
            }
        });
        getContentPane().add(jButtonK, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, 44, 31));

        jButtonL.setText("L");
        jButtonL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonLMousePressed(evt);
            }
        });
        getContentPane().add(jButtonL, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 42, 31));

        jButtonM.setText("M");
        jButtonM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonMMousePressed(evt);
            }
        });
        jButtonM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, 40, 31));

        jButtonN.setText("N");
        jButtonN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonNMousePressed(evt);
            }
        });
        jButtonN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 41, 31));

        jButtonÑ.setText("Ñ");
        jButtonÑ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonÑMousePressed(evt);
            }
        });
        getContentPane().add(jButtonÑ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, -1, 31));

        jButtonO.setText("O");
        jButtonO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonOMousePressed(evt);
            }
        });
        getContentPane().add(jButtonO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 580, 40, 31));

        jButtonP.setText("P");
        jButtonP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonPMousePressed(evt);
            }
        });
        getContentPane().add(jButtonP, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 42, 31));

        jButtonQ.setText("Q");
        jButtonQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonQMousePressed(evt);
            }
        });
        getContentPane().add(jButtonQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 580, 44, 31));

        jButtonR.setText("R");
        jButtonR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonRMousePressed(evt);
            }
        });
        jButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 42, 31));

        jButtonS.setText("S");
        jButtonS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonSMousePressed(evt);
            }
        });
        getContentPane().add(jButtonS, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 580, 40, 31));

        jButtonT.setText("T");
        jButtonT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonTMousePressed(evt);
            }
        });
        getContentPane().add(jButtonT, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 41, 31));

        jButtonU.setText("U");
        jButtonU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonUMousePressed(evt);
            }
        });
        jButtonU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, 31));

        jButtonV.setText("V");
        jButtonV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonVMousePressed(evt);
            }
        });
        getContentPane().add(jButtonV, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 620, 40, 31));

        jButtonW.setText("W");
        jButtonW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonWMousePressed(evt);
            }
        });
        getContentPane().add(jButtonW, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 620, 42, 31));

        jButtonX.setText("X");
        jButtonX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonXMousePressed(evt);
            }
        });
        getContentPane().add(jButtonX, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 620, 42, 31));

        jButtonY.setText("Y");
        jButtonY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonYMousePressed(evt);
            }
        });
        getContentPane().add(jButtonY, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 620, 40, 31));

        jButtonZ.setText("Z");
        jButtonZ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonZMousePressed(evt);
            }
        });
        getContentPane().add(jButtonZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 620, 41, 31));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonAMousePressed

    private void jButtonHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonHMousePressed

    private void jButtonÑMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonÑMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonÑMousePressed

    private void jButtonUMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonUMousePressed

    private void jButtonFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFActionPerformed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonFActionPerformed

    private void jButtonJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJActionPerformed

    }//GEN-LAST:event_jButtonJActionPerformed

    private void jButtonMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMActionPerformed

    }//GEN-LAST:event_jButtonMActionPerformed

    private void jButtonNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNActionPerformed

    }//GEN-LAST:event_jButtonNActionPerformed

    private void jButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRActionPerformed

    }//GEN-LAST:event_jButtonRActionPerformed

    private void jButtonUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUActionPerformed

    }//GEN-LAST:event_jButtonUActionPerformed

    private void jButtonBMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonBMousePressed

    private void jButtonCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonCMousePressed

    private void jButtonEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonEMousePressed

    private void jButtonDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonDMousePressed

    private void jButtonGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonGMousePressed

    private void jButtonFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonFMousePressed

    private void jButtonIMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonIMousePressed

    private void jButtonJMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonJMousePressed

    private void jButtonKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonKMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonKMousePressed

    private void jButtonLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonLMousePressed

    private void jButtonMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonMMousePressed

    private void jButtonNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonNMousePressed

    private void jButtonOMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonOMousePressed

    private void jButtonPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonPMousePressed

    private void jButtonQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonQMousePressed

    private void jButtonRMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonRMousePressed

    private void jButtonSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonSMousePressed

    private void jButtonTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonTMousePressed

    private void jButtonVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonVMousePressed

    private void jButtonWMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonWMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonWMousePressed

    private void jButtonXMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonXMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonXMousePressed

    private void jButtonYMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonYMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonYMousePressed

    private void jButtonZMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonZMousePressed
        chequeaLetra((JButton) evt.getSource());
    }//GEN-LAST:event_jButtonZMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonA;
    private javax.swing.JButton jButtonB;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonD;
    private javax.swing.JButton jButtonE;
    private javax.swing.JButton jButtonF;
    private javax.swing.JButton jButtonG;
    private javax.swing.JButton jButtonH;
    private javax.swing.JButton jButtonI;
    private javax.swing.JButton jButtonJ;
    private javax.swing.JButton jButtonK;
    private javax.swing.JButton jButtonL;
    private javax.swing.JButton jButtonM;
    private javax.swing.JButton jButtonN;
    private javax.swing.JButton jButtonO;
    private javax.swing.JButton jButtonP;
    private javax.swing.JButton jButtonQ;
    private javax.swing.JButton jButtonR;
    private javax.swing.JButton jButtonS;
    private javax.swing.JButton jButtonT;
    private javax.swing.JButton jButtonU;
    private javax.swing.JButton jButtonV;
    private javax.swing.JButton jButtonW;
    private javax.swing.JButton jButtonX;
    private javax.swing.JButton jButtonY;
    private javax.swing.JButton jButtonZ;
    private javax.swing.JButton jButtonÑ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
